### PR TITLE
v0.2.0

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
@AdrianSosic @ngam Please do not merge to main; https://github.com/conda-forge/ax-platform-feedstock/pull/11 needs backward compatibility for linear-operator 0.2.0, hence this PR. If possible please merge into a 0.2.0 branch on the repo. Thanks!

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
Did we not have 0.2.0 before? It seems we did: https://anaconda.org/conda-forge/linear_operator/files

let me know what you think

**Comment by ngam** [comment]
Moved to draft because I think this is not needed...

**Comment by thewchan** [comment]
@ngam thanks I think this is my bad I totally should have thought of the `_` vs `-` thing

**Pull request closed without merging**
